name: weather_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  get: 4.6.6
  location: ^5.0.0
  get_storage: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.6

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
